apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: auth-microservice-secret
  namespace: statex-apps
spec:
  refreshInterval: 5m
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: auth-microservice-secret
    creationPolicy: Owner
  data:
    - secretKey: DB_PASSWORD
      remoteRef:
        key: secret/prod/auth-microservice
        property: DB_PASSWORD
    - secretKey: JWT_SECRET
      remoteRef:
        key: secret/prod/auth-microservice
        property: JWT_SECRET
    - secretKey: TEST_EMAIL
      remoteRef:
        key: secret/prod/auth-microservice
        property: TEST_EMAIL
    - secretKey: TEST_PASSWORD
      remoteRef:
        key: secret/prod/auth-microservice
        property: TEST_PASSWORD
    - secretKey: GOOGLE_CLIENT_ID
      remoteRef:
        key: secret/prod/auth-microservice
        property: GOOGLE_CLIENT_ID
    - secretKey: GOOGLE_CLIENT_SECRET
      remoteRef:
        key: secret/prod/auth-microservice
        property: GOOGLE_CLIENT_SECRET
    - secretKey: FACEBOOK_CLIENT_ID
      remoteRef:
        key: secret/prod/auth-microservice
        property: FACEBOOK_CLIENT_ID
    - secretKey: FACEBOOK_CLIENT_SECRET
      remoteRef:
        key: secret/prod/auth-microservice
        property: FACEBOOK_CLIENT_SECRET
